apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: Spring Music
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/name: spring-music
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/fklein82/spring-music-master-accelerator
      ref:
        branch: main
  serviceClaims:
  - name: music-database
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: postgresql-secret
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
